version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
