[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NIXPACKS_NODE_VERSION = "20"

[[volumes]]
mountPath = "/data"
